### ISSUE TITLE
DetailLayout：Rendered more hooks than during the previous render

### ISSUE THREAD

**Issue by leegent** [blacklake-web/foundation#19]
### 描述
`<DetailLayout>`的`info` prop，初次渲染时传1个元素，请求后端接口后渲染时传2个元素，报错如题。

### 原因分析
DetailLayoutContent.tsx 里，`useSize`里面的`React.useState`等hook，仍然属于`<DetailLayoutContent>`组件的作用域，当`info`的元素数量发生变化时，hook数量也会跟着变化，导致报错。

### 建议
将`useSize`的逻辑写到`RenderInfoBlock`内部；或者提到`DetailLayoutContent`的顶级，不要放在map里

**Comment by zxlsr** [comment]
已经修复到1.0.14-alpha.21版本了
